// This test file was generated by AI.

import Testing

@testable import BrassBand

@MainActor
struct ComponentsTests {
    @Test("Componentsの初期化")
    func initialize() throws {
        // ViewLookとMetalSystemのモックを作成
        let viewLook = ViewLook()
        let device = try #require(MTLCreateSystemDefaultDevice())
        let view = MetalView()
        let system = try #require(MetalSystem(device: device, view: view))

        // Componentsを初期化
        let components = Components(viewLook: viewLook, system: system)

        // 各プロパティが正しく初期化されていることを確認
        #expect(components.viewLook === viewLook)
        #expect(components.system === system)
        #expect(components.rootNode.parent === viewLook)
    }
}
